# Generated by Django 6.0.2 on 2026-03-25 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('ville', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('agrement', models.CharField(max_length=100)),
                ('valide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('quantite', models.PositiveIntegerField()),
                ('delai', models.DateTimeField()),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('groupes_cibles', models.CharField(max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.TimeField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.donneur')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('demande_urgente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.demandeurgente')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniProjet.donneur')),
            ],
        ),
    ]
