# Generated by Django 6.0.2 on 2026-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProjet', '0003_notification_expediteur_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
