# Generated by Django 6.0.2 on 2026-02-28 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_produitnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCde', models.DateField(default=datetime.date.today, null=True)),
                ('totalCde', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='im',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
