# Generated by Django 6.0.2 on 2026-02-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_commande_produit_im'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='im',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
