# Generated by Django 6.0.2 on 2026-03-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_remove_produit_im_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
