# Generated by Django 6.0.2 on 2026-04-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_alter_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('em', 'emballe'), ('fr', 'Frais'), ('cs', 'Conserve')], default='em', max_length=100),
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='magasin.commande')),
            ],
        ),
    ]
