# Generated by Django 6.0.2 on 2026-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='solde',
            field=models.PositiveIntegerField(default=0, help_text='Remise en % (0 = pas de solde)'),
        ),
    ]
